In [9]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
file_path = "data/zhvi_data.csv"
home_values_df=pd.read_csv(file_path)

home_values_df.head()

,RegionName,RegionType,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2017-01-31,2017-02-28,2017-03-31,2017-04-30,...,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31
0,Los Angeles County,County,CA,Los Angeles-Long Beach-Anaheim,6,37,567167.0,570020.0,573344.0,575480.0,...,659773.0,664580.0,666444.0,667704.0,672758.0,680207.0,688570.0,695441.0,702046.0,708045.0
1,Cook County,County,IL,Chicago-Naperville-Elgin,17,31,235165.0,235814.0,237493.0,238830.0,...,253684.0,254076.0,254595.0,255333.0,256710.0,258486.0,261016.0,263754.0,266201.0,268475.0
2,Harris County,County,TX,Houston-The Woodlands-Sugar Land,48,201,177989.0,178366.0,178869.0,179782.0,...,199807.0,200940.0,201912.0,202637.0,203555.0,204670.0,206514.0,208295.0,210494.0,212658.0
3,Maricopa County,County,AZ,Phoenix-Mesa-Scottsdale,4,13,242028.0,243189.0,244568.0,245814.0,...,299209.0,302766.0,305996.0,309005.0,311980.0,315932.0,320662.0,325809.0,331342.0,337118.0
4,San Diego County,County,CA,San Diego-Carlsbad,6,73,528758.0,531624.0,536251.0,542424.0,...,615413.0,618539.0,622620.0,625616.0,629734.0,636244.0,645855.0,656702.0,667613.0,678665.0

In [12]:
fl_filter=home_values_df['State']=="FL"
fl_df=home_values_df[fl_filter]
display(fl_df)

,RegionName,RegionType,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2017-01-31,2017-02-28,2017-03-31,2017-04-30,...,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31
7,Miami-Dade County,County,FL,Miami-Fort Lauderdale-West Palm Beach,12,86,280519.0,282088.0,283345.0,284333.0,...,321646.0,322667.0,323839.0,325073.0,326723.0,328699.0,331112.0,333362.0,335250.0,338247.0
17,Broward County,County,FL,Miami-Fort Lauderdale-West Palm Beach,12,11,238467.0,239408.0,240264.0,242297.0,...,280189.0,281858.0,283653.0,285358.0,286276.0,287859.0,289936.0,292873.0,295927.0,299361.0
27,Palm Beach County,County,FL,Miami-Fort Lauderdale-West Palm Beach,12,99,260005.0,261593.0,262799.0,263942.0,...,296701.0,297792.0,298258.0,299202.0,300753.0,303061.0,306233.0,308960.0,311423.0,313980.0
29,Hillsborough County,County,FL,Tampa-St. Petersburg-Clearwater,12,57,203932.0,205139.0,206259.0,208159.0,...,244753.0,246250.0,247704.0,249634.0,251471.0,253868.0,256269.0,258750.0,261279.0,264290.0
34,Orange County,County,FL,Orlando-Kissimmee-Sanford,12,95,222605.0,224662.0,226823.0,228648.0,...,273809.0,275465.0,276998.0,278675.0,280057.0,281701.0,283155.0,285058.0,286748.0,288595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,Calhoun County,County,FL,NaN,12,13,91432.0,91912.0,92173.0,92959.0,...,104501.0,104658.0,105155.0,105710.0,106210.0,106432.0,106733.0,107042.0,107650.0,107998.0
2229,Glades County,County,FL,NaN,12,43,117671.0,117857.0,118352.0,118849.0,...,136742.0,137138.0,137688.0,138287.0,138843.0,139270.0,139796.0,140244.0,140668.0,140645.0
2304,Franklin County,County,FL,NaN,12,37,250079.0,251298.0,252214.0,253003.0,...,280946.0,281489.0,283005.0,284538.0,285835.0,286675.0,288092.0,289743.0,291576.0,293245.0
2492,Lafayette County,County,FL,NaN,12,67,108726.0,109147.0,109331.0,109683.0,...,130005.0,130578.0,131778.0,133074.0,134008.0,134388.0,134913.0,135778.0,136409.0,137248.0
2537,Liberty County,County,FL,NaN,12,77,100849.0,101332.0,101996.0,102592.0,...,123122.0,122723.0,122637.0,122971.0,123509.0,123627.0,123460.0,123333.0,123424.0,123775.0

In [14]:
price_percent_columns=['2017-01-31', '2020-02-29', '2020-03-31', '2020-12-31']
monroe_price_percent=fl_df.loc[fl_filter, price_percent_columns]
monroe_price_percent
pre_covid_price=((monroe_price_percent['2020-02-29']-monroe_price_percent['2017-01-31'])/monroe_price_percent['2020-02-29'])/3
pre_covid_price

7       0.041521
17      0.048467
27      0.039932
29      0.054261
34      0.060888
          ...
2124    0.041938
2229    0.045495
2304    0.036250
2492    0.053191
2537    0.060509
Length: 67, dtype: float64